In [1]:
# Import deepos
import deepops as dp

In [2]:
# make Tensors
a = dp.tensor([1.0]*100000)
b = dp.tensor([2.0]*100000)

In [3]:
# throw these Tensors in our precious GPU
a.device('gpu') # i.e gpu:0
b.device('gpu')

In [4]:
# add them on GPU
addition = a.add(b)

In [5]:
# print the Addition
addition

array([3., 3., 3., ..., 3., 3., 3.], dtype=float32)

In [6]:
# adds beautifully with itself!
a.add(a)

array([2., 2., 2., ..., 2., 2., 2.], dtype=float32)

In [7]:
print(a + a)

[2. 2. 2. ... 2. 2. 2.]


In [9]:
a

dp.Tensor shape=self.shape, numpy=([1. 1. 1. ... 1. 1. 1.], dtype=float32)