In [11]:
# Import deepos
import deepops as dp

In [ ]:
# make Tensors
a = dp.Tensor([1.0]*100000)
b = dp.Tensor([2.0]*100000)

In [14]:
# Tensor Operations on CPU
print("Add:", a+b, "Mul:", a*b)

Add: [3. 3. 3. ... 3. 3. 3.] Mul: [2. 2. 2. ... 2. 2. 2.]


In [13]:
# Default Device is cpu
a

dp.Tensor shape: (100000,), numpy: ([1. 1. 1. ... 1. 1. 1.], dtype=float32), cuda device: cpu 

In [3]:
# throw these Tensors in our precious GPU
a.device('gpu') # i.e gpu:0
b.device('gpu')

dp.Tensor shape: (100000,), numpy: ([2. 2. 2. ... 2. 2. 2.], dtype=float32), cuda device: gpu 

In [4]:
# add them on GPU
addition = a.add(b)

In [5]:
# print the Addition
addition

array([3., 3., 3., ..., 3., 3., 3.], dtype=float32)

In [6]:
# adds beautifully with itself!
a.add(a)

array([2., 2., 2., ..., 2., 2., 2.], dtype=float32)

In [7]:
print(a + a)

[2. 2. 2. ... 2. 2. 2.]


In [8]:
print(a * b)

[2. 2. 2. ... 2. 2. 2.]


In [9]:
repr(a)

'dp.Tensor shape: (100000,), numpy: ([1. 1. 1. ... 1. 1. 1.], dtype=float32), cuda device: gpu '